<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rp_assignment</name>
  <version>0.1.0</version>
  <description>
   robotics project for RGB-D based pothole detection and 3D localisation,
  LiDAR-based obstacle handling, and Nav2 waypoint navigation on an AgileX LIMO platform.
</description>
  <maintainer email="deepakjowel05@gmail.com">dpk</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <!--<exec_depend>rospy</exec_depend>-->
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
   <exec_depend>tf_transformations</exec_depend>
  <exec_depend>nav2_simple_commander</exec_depend>  
 
  
    
    
  
  <!-- <test_depend>rclcpp</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>geometry_msg</test_depend> -->


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
